import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Locale, locales } from '@/i18n'
import { unstable_setRequestLocale } from 'next-intl/server'

const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

// @todo: add metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type PageProps = Readonly<{
  children: React.ReactNode
  params: { locale: Locale }
}>

export default function LocaleLayout({
  children,
  params: { locale },
}: PageProps) {
  unstable_setRequestLocale(locale)

  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
